In [2]:
import pkg_resources

In [3]:
dists = [d for d in pkg_resources.working_set]
for i in dists:
    print(i)

zipp 0.6.0
zict 1.0.0
xmltodict 0.12.0
xlwt 1.3.0
xlwings 0.15.10
XlsxWriter 1.2.1
xlrd 1.2.0
wrapt 1.11.2
wincertstore 0.2
win-unicode-console 0.5
win-inet-pton 1.1.0
widgetsnbextension 3.5.1
wheel 0.33.6
Werkzeug 0.16.0
websocket-client 0.48.0
webencodings 0.5.1
wcwidth 0.1.7
vega-datasets 0.8.0
urllib3 1.24.2
unicodecsv 0.14.1
typing-extensions 3.7.4.3
traitlets 4.3.3
tqdm 4.36.1
tornado 6.0.3
toolz 0.10.0
testpath 0.4.2
terminado 0.8.2
termcolor 1.1.0
tensorflow 1.15.0
tensorflow-estimator 1.15.1
tensorboard 1.15.0
tblib 1.4.0
tables 3.5.2
sympy 1.4
statsmodels 0.10.1
sqlparse 0.3.0
SQLAlchemy 1.3.9
spyder 3.3.6
spyder-kernels 0.5.2
sphinxcontrib-websupport 1.1.2
sphinxcontrib-serializinghtml 1.1.3
sphinxcontrib-qthelp 1.0.2
sphinxcontrib-jsmath 1.0.1
sphinxcontrib-htmlhelp 1.0.2
sphinxcontrib-devhelp 1.0.1
sphinxcontrib-applehelp 1.0.1
Sphinx 2.2.0
speedtest-cli 2.1.2
soupsieve 1.9.3
sortedcontainers 2.1.0
sortedcollections 1.1.2
snowballstemmer 2.0.0
sklearn 0.0
six 1.12.0
single

In [4]:
import nltk
import re

In [5]:
string01 = "Budi dan Badu bermain bola di sekolah"
string02 = "Apakah Romi dan Julia saling mencintai saat mereka berjumpa di persimpangan jalan?"

In [6]:
def tokenize_clean(text):
    
    #tokenisasi
    tokens = [word.lower() for sent in nltk.sent_tokenize(text) for word
        in nltk.word_tokenize(sent)]
    
    #clean token from numeric and other character like punctuation
    filtered_tokens = []
    for token in tokens:
        if re.search('[a-zA-Z]', token):
            filtered_tokens.append(token)
            
    return filtered_tokens

In [7]:
result01 = tokenize_clean(string01)
print(string01)
print(result01)

Budi dan Badu bermain bola di sekolah
['budi', 'dan', 'badu', 'bermain', 'bola', 'di', 'sekolah']


In [8]:
result02 = tokenize_clean(string02)
print(string02)
print(result02)

Apakah Romi dan Julia saling mencintai saat mereka berjumpa di persimpangan jalan?
['apakah', 'romi', 'dan', 'julia', 'saling', 'mencintai', 'saat', 'mereka', 'berjumpa', 'di', 'persimpangan', 'jalan']


In [9]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Fajri\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [10]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Fajri\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [11]:
stopwords = nltk.corpus.stopwords.words('indonesian')

In [12]:
stopwords

['ada',
 'adalah',
 'adanya',
 'adapun',
 'agak',
 'agaknya',
 'agar',
 'akan',
 'akankah',
 'akhir',
 'akhiri',
 'akhirnya',
 'aku',
 'akulah',
 'amat',
 'amatlah',
 'anda',
 'andalah',
 'antar',
 'antara',
 'antaranya',
 'apa',
 'apaan',
 'apabila',
 'apakah',
 'apalagi',
 'apatah',
 'artinya',
 'asal',
 'asalkan',
 'atas',
 'atau',
 'ataukah',
 'ataupun',
 'awal',
 'awalnya',
 'bagai',
 'bagaikan',
 'bagaimana',
 'bagaimanakah',
 'bagaimanapun',
 'bagi',
 'bagian',
 'bahkan',
 'bahwa',
 'bahwasanya',
 'baik',
 'bakal',
 'bakalan',
 'balik',
 'banyak',
 'bapak',
 'baru',
 'bawah',
 'beberapa',
 'begini',
 'beginian',
 'beginikah',
 'beginilah',
 'begitu',
 'begitukah',
 'begitulah',
 'begitupun',
 'bekerja',
 'belakang',
 'belakangan',
 'belum',
 'belumlah',
 'benar',
 'benarkah',
 'benarlah',
 'berada',
 'berakhir',
 'berakhirlah',
 'berakhirnya',
 'berapa',
 'berapakah',
 'berapalah',
 'berapapun',
 'berarti',
 'berawal',
 'berbagai',
 'berdatangan',
 'beri',
 'berikan',
 'berikut'

In [13]:
def remove_stopwords(tokenized_text):
    
    cleaned_token = []
    for token in tokenized_text:
        if token not in stopwords:
            cleaned_token.append(token)
            
    return cleaned_token

In [14]:
result01 = tokenize_clean(string01)
result1 = remove_stopwords(result01)
print(string01)
print(result01)
print(result1)

Budi dan Badu bermain bola di sekolah
['budi', 'dan', 'badu', 'bermain', 'bola', 'di', 'sekolah']
['budi', 'badu', 'bermain', 'bola', 'sekolah']


In [15]:
result02 = tokenize_clean(string01)
result2 = remove_stopwords(result01)
print(string02)
print(result02)
print(result2)

Apakah Romi dan Julia saling mencintai saat mereka berjumpa di persimpangan jalan?
['budi', 'dan', 'badu', 'bermain', 'bola', 'di', 'sekolah']
['budi', 'badu', 'bermain', 'bola', 'sekolah']


In [16]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

In [17]:
def stemming_text(tokenized_text):
    
    factory = StemmerFactory()
    stemmer = factory.create_stemmer()
    
    stems = []
    for token in tokenized_text:
        stems.append(stemmer.stem(token))
        
    return stems

In [18]:
result01 = tokenize_clean(string01)
result1 = remove_stopwords(result01)
stem_result1 = stemming_text(result1)
print(string01)
print(result01)
print(result1)
print(stem_result1)

Budi dan Badu bermain bola di sekolah
['budi', 'dan', 'badu', 'bermain', 'bola', 'di', 'sekolah']
['budi', 'badu', 'bermain', 'bola', 'sekolah']
['budi', 'badu', 'main', 'bola', 'sekolah']


In [19]:
result02 = tokenize_clean(string02)
result2 = remove_stopwords(result02)
stem_result2 = stemming_text(result2)
print(string02)
print(result02)
print(result2)
print(stem_result2)

Apakah Romi dan Julia saling mencintai saat mereka berjumpa di persimpangan jalan?
['apakah', 'romi', 'dan', 'julia', 'saling', 'mencintai', 'saat', 'mereka', 'berjumpa', 'di', 'persimpangan', 'jalan']
['romi', 'julia', 'mencintai', 'berjumpa', 'persimpangan', 'jalan']
['romi', 'julia', 'cinta', 'jumpa', 'simpang', 'jalan']


In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [21]:
def text_preprocessing(text):
    
    prep01 = tokenize_clean(text)
    prep02 = remove_stopwords(prep01)
    prep03 = stemming_text(prep02)
    
    return prep03

In [22]:
text_preprocessing(string02)

['romi', 'julia', 'cinta', 'jumpa', 'simpang', 'jalan']

In [23]:
text_preprocessing(string01)

['budi', 'badu', 'main', 'bola', 'sekolah']

In [24]:
corpus = [
     'kucing kucing kucing hitam putih belang',
     'tikus belang',
     'tikus hitam',
     'tikus tikus tikus'
]


In [25]:
len(corpus)

4

In [26]:
corpus[1]

'tikus belang'

In [27]:
vectorizer = TfidfVectorizer(use_idf=True)
X = vectorizer.fit_transform(corpus)

In [28]:
vectorizer

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [29]:
X

<4x5 sparse matrix of type '<class 'numpy.float64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [30]:
print(X.shape)

(4, 5)


In [31]:
print(vectorizer.get_feature_names())

['belang', 'hitam', 'kucing', 'putih', 'tikus']


In [32]:
print(X.toarray())

[[0.23513012 0.23513012 0.89469821 0.29823274 0.        ]
 [0.77722116 0.         0.         0.         0.62922751]
 [0.         0.77722116 0.         0.         0.62922751]
 [0.         0.         0.         0.         1.        ]]


In [33]:
print(X[0])

  (0, 0)	0.2351301157996824
  (0, 3)	0.2982327375202219
  (0, 1)	0.2351301157996824
  (0, 2)	0.8946982125606657


In [34]:
print(X[0].toarray())

[[0.23513012 0.23513012 0.89469821 0.29823274 0.        ]]


In [35]:
import pandas as pd

In [36]:
df = pd.DataFrame(X[1].T.todense(), index=vectorizer.get_feature_names(), columns=['TF-IDF'])
df.sort_values(by=['TF-IDF'])

TF-IDF
hitam   0.000000
kucing  0.000000
putih   0.000000
tikus   0.629228
belang  0.777221

In [37]:
df_idf = pd.DataFrame(vectorizer.idf_, index=vectorizer.get_feature_names(), columns=['idf'])
df_idf.sort_values(by=['idf'])


idf
tikus   1.223144
belang  1.510826
hitam   1.510826
kucing  1.916291
putih   1.916291

In [38]:
str1 = "Kambing hitam"
response = vectorizer.transform([str1])

feature_names = vectorizer.get_feature_names()

In [39]:
feature_names

['belang', 'hitam', 'kucing', 'putih', 'tikus']

In [40]:
response.toarray()

array([[0., 1., 0., 0., 0.]])

In [41]:
files = []
files.append("Sekelompok ibu dan kaum perempuan duduk beralaskan rumput lapangan sambil fokus menganyam bambu yang ia genggam ditangan.")
files.append("Sebagian besar masyarakat rupanya tak mau melewatkan waktu begitu  saja untuk meratapi erupsi.")
files.append("Lombok memang memiliki sejuta pesona yang mampu menyedot perhatian orang untuk datang berwisata.")
files.append("Perempuan yang bergelut di dunia kerelawanan akan belajar caranya bertanggung jawab bagi sendiri dan orang lain.")
files.append("Kami berkoordinasi dan melapor pada posko relawan, kami berkomitmen  siap membantu dengan siaga 24 jam")

In [42]:
token_dict = {}
i = 0
for t in files:
    filename = "file" + str(i)
    token_dict[filename] = t
    i = i + 1

token_dict


{'file0': 'Sekelompok ibu dan kaum perempuan duduk beralaskan rumput lapangan sambil fokus menganyam bambu yang ia genggam ditangan.',
 'file1': 'Sebagian besar masyarakat rupanya tak mau melewatkan waktu begitu  saja untuk meratapi erupsi.',
 'file2': 'Lombok memang memiliki sejuta pesona yang mampu menyedot perhatian orang untuk datang berwisata.',
 'file3': 'Perempuan yang bergelut di dunia kerelawanan akan belajar caranya bertanggung jawab bagi sendiri dan orang lain.',
 'file4': 'Kami berkoordinasi dan melapor pada posko relawan, kami berkomitmen  siap membantu dengan siaga 24 jam'}

In [43]:
token_dict.values()

dict_values(['Sekelompok ibu dan kaum perempuan duduk beralaskan rumput lapangan sambil fokus menganyam bambu yang ia genggam ditangan.', 'Sebagian besar masyarakat rupanya tak mau melewatkan waktu begitu  saja untuk meratapi erupsi.', 'Lombok memang memiliki sejuta pesona yang mampu menyedot perhatian orang untuk datang berwisata.', 'Perempuan yang bergelut di dunia kerelawanan akan belajar caranya bertanggung jawab bagi sendiri dan orang lain.', 'Kami berkoordinasi dan melapor pada posko relawan, kami berkomitmen  siap membantu dengan siaga 24 jam'])

In [44]:
token_dict['file0']

'Sekelompok ibu dan kaum perempuan duduk beralaskan rumput lapangan sambil fokus menganyam bambu yang ia genggam ditangan.'

In [45]:
#perform tf-idf vectorization
tfidf = TfidfVectorizer(max_df=0.8,             # terms with document frequency value > 0.8 will be removed
                        min_df=0.2,             # terms with document frequency value < 0.2 will be removed
                        max_features=200000,    # create maximum 200.000 vocabulary that only consider the top max_features ordered by term frequency across the corpus.
                        stop_words = stopwords, # stopwords list
                        use_idf=True,           # enable inverse-document-frequency reweighting
                        tokenizer=text_preprocessing, # override the string tokenization step by using text_prepocessing function 
                        ngram_range=(1,3))      # ngram range 1 - 3 


tfs = tfidf.fit_transform(token_dict.values())


In [46]:
tfs.shape

(5, 96)

In [47]:
print(tfs[0])

  (0, 11)	0.17500574860015006
  (0, 8)	0.17500574860015006
  (0, 24)	0.17500574860015006
  (0, 48)	0.17500574860015006
  (0, 86)	0.17500574860015006
  (0, 5)	0.17500574860015006
  (0, 17)	0.17500574860015006
  (0, 65)	0.17500574860015006
  (0, 36)	0.17500574860015006
  (0, 39)	0.17500574860015006
  (0, 29)	0.17500574860015006
  (0, 10)	0.17500574860015006
  (0, 7)	0.17500574860015006
  (0, 23)	0.17500574860015006
  (0, 47)	0.17500574860015006
  (0, 85)	0.17500574860015006
  (0, 4)	0.17500574860015006
  (0, 16)	0.17500574860015006
  (0, 64)	0.17500574860015006
  (0, 35)	0.17500574860015006
  (0, 38)	0.17500574860015006
  (0, 92)	0.17500574860015006
  (0, 28)	0.17500574860015006
  (0, 9)	0.17500574860015006
  (0, 6)	0.17500574860015006
  (0, 22)	0.17500574860015006
  (0, 46)	0.17500574860015006
  (0, 84)	0.17500574860015006
  (0, 3)	0.17500574860015006
  (0, 15)	0.17500574860015006
  (0, 63)	0.1411935360448027
  (0, 34)	0.17500574860015006
  (0, 37)	0.17500574860015006


In [48]:
feature_names = tfidf.get_feature_names()

In [49]:
print(feature_names)

['ajar', 'ajar tanggung', 'ajar tanggung orang', 'alas', 'alas rumput', 'alas rumput lapang', 'anyam', 'anyam bambu', 'anyam bambu genggam', 'bambu', 'bambu genggam', 'bambu genggam tang', 'bantu', 'bantu siaga', 'bantu siaga jam', 'duduk', 'duduk alas', 'duduk alas rumput', 'dunia', 'dunia rawan', 'dunia rawan ajar', 'erupsi', 'fokus', 'fokus anyam', 'fokus anyam bambu', 'gelut', 'gelut dunia', 'gelut dunia rawan', 'genggam', 'genggam tang', 'jam', 'juta', 'juta pesona', 'juta pesona sedot', 'kaum', 'kaum perempuan', 'kaum perempuan duduk', 'kelompok', 'kelompok kaum', 'kelompok kaum perempuan', 'komitmen', 'komitmen bantu', 'komitmen bantu siaga', 'koordinasi', 'koordinasi lapor', 'koordinasi lapor posko', 'lapang', 'lapang fokus', 'lapang fokus anyam', 'lapor', 'lapor posko', 'lapor posko rawan', 'lombok', 'lombok milik', 'lombok milik juta', 'masyarakat', 'masyarakat ratap', 'masyarakat ratap erupsi', 'milik', 'milik juta', 'milik juta pesona', 'orang', 'orang wisata', 'perempuan',

In [50]:
df_idf = pd.DataFrame(tfidf.idf_, index=feature_names,columns=["idf"])
df_idf.sort_values(by=['idf'])

idf
rawan              1.693147
perempuan          1.693147
orang              1.693147
ajar               2.098612
perhati            2.098612
...                     ...
gelut dunia rawan  2.098612
gelut dunia        2.098612
gelut              2.098612
tanggung orang     2.098612
wisata             2.098612

[96 rows x 1 columns]